import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import api from "~/utils/api";
import mqtt from 'mqtt';


const Home: NextPage = () => {
  const [status, setStatus] = useState("");
  const [connectionStatus, setConnectionStatus] = useState(false);
  const [messages, setMessages] = useState<string[]>([]);

  useEffect(() => {
    const client = mqtt.connect('');
    client.on("connect", () => setConnectionStatus(true));
    client.on("message", (topic, payload, packet) => {
      setMessages(messages.concat(payload.toString()));
    });
  }, []);

  const alphabet = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ];

  function createSignal(params: string) {
    api.get("/" + params);
  }

  return (
    <>
      <Head>
        <title>Interface</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="">
        <h1 className="text-center text-4xl font-bold">
          {" "}
          Ensinador de braille:{" "}
        </h1>
        <h1 className="text-center text-4xl font-bold"> Escolha a letra</h1>
        <div className="">
          {" "}
          {alphabet.map((letter) => {
            if (status === letter) {
              return (
                <button
                  className="m-6 h-20 w-32 rounded-lg bg-red-500 text-xl font-bold text-white"
                  onClick={() => {
                    createSignal(letter);
                    setStatus(letter);
                  }}
                >
                  {letter}
                </button>
              );
            } else {
              return (
                <button
                  className="m-6 h-20 w-32 rounded-lg bg-green-500 text-xl font-bold text-white"
                  onClick={() => {
                    createSignal(letter);
                    setStatus(letter);
                  }}
                >
                  {letter}
                </button>
              );
            }
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
